AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Basic static website deployment boilerplate

Parameters:
  SiteBucketName:
    Type: String
    Description: Unique name for S3 bucket
  DomainName:
    Type: String
    Description: >
      Install nodejs server that logs locally to the instance and responds with the hostname
  HostedZoneName:
    Type: String
    Description: Qualified Hosted Zone Name
  CertificateARN:
    Type: String
    Description: Full ARN of ACM certificate

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: SiteBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: SiteBucket
      PolicyDocument:
        Statement:
          - 
            Action:
              - 's3:GetObject'
            Effect: "Allow"
            Principal: '*'
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: SiteBucket
                  - "/*"
  SiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - SiteBucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to UI static website S3 bucket
        Origins:
        - DomainName: !Select [ 2, !Split ["/", !GetAtt SiteBucket.WebsiteURL] ]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - Ref: DomainName
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:742666682568:certificate/7906beb2-18c3-4629-a2ed-1718472d1091'
          SslSupportMethod: sni-only

  PublicDNS:
    Type: AWS::Route53::RecordSet
    Properties: 
      HostedZoneName:
        Ref: HostedZoneName
      Name:
        Ref: DomainName
      Region: "us-east-1"
      Type: A
      AliasTarget:
        HostedZoneId: 'Z2FDTNDATAQYW2'
        DNSName: !GetAtt [ SiteCloudfront, DomainName ]
      SetIdentifier:
        Ref: DomainName
